### PR TITLE
Additional handling of device state in async_update function

### PR DESCRIPTION
**Pull request by steve-hodgkiss**
Changes to the async_update function on major API changes to reduce API calls on events. Seems to cope with keeping the state in HA sync'd with what home connect has on their end. Tested on the following device types: coffee machine, oven, hob, washing machine and dryer.
Reduces API calls every 24 hours by about 50 to 75%.

### CODE REVIEW

**Review by ekutner — COMMENTED** [review]
Thank you. It looks interesting but to be honest I don't quite understand the motivation behind a lot of the changes.
I could use a lot more explanation/comments on the motivation behind these changes and what appliance states have you encountered that makes them correct. I think it would be good to start with the different states and why you decided to break out the active/inactive states and then go into more details on the other changes.

I only did d very brief review but a lot of questions came to mind. For example. why is it ok not to update the available_programs and selected_program when a new active program event is received. Or when a RemoteControlStartAllowed event is received why is it ok to only fethc the available_programs if it's currently None ? 

Once I get the general idea behind your changes we can move to review comments to discuss the handling of specific events.

**Comment by steve-hodgkiss** [comment]
Hi - thanks for looking at the PR. As a general rule I don't tend to find that the list of programs or settings changes for a given state. The event stream tends to be pretty good at telling us what's going on. It's the commands available that changes (e.g. start, stop, pause). For the operation states https://api-docs.home-connect.com/states/?#operation-state I'm using the docs as a guide.

For example when the appliance is Inactive, there will be no active program. Similar for Ready. Run & Pause will have an active program.

So I tried to break the states into groups : On vs Off vs Running vs Error. That sort of approach...

**Comment by ekutner** [comment]
> Hi - thanks for looking at the PR. As a general rule I don't tend to find that the list of programs or settings changes for a given state. The event stream tends to be pretty good at telling us what's going on. It's the commands available that changes (e.g. start, stop, pause). For the operation states [api-docs.home-connect.com/states/?#operation-state](https://api-docs.home-connect.com/states/?#operation-state) I'm using the docs as a guide.

In general, the stream sends updates about read only properties, but it doesn't say anything about settable properties such as available programs or settings. To be fair, I don't think I've ever seen the available settings change with the operation state, and that was fetched out of extra caution, but the available programs definitely change with different states. 

> 
> For example when the appliance is Inactive, there will be no active program. Similar for Ready. Run & Pause will have an active program.

That makes sense, however there are additional scenarios that need to be covered because the event stream is not 100% reliable and sometimes events are missed., so it's important not to assume the current operation state is correct when receiving events that imply a different state.

> So I tried to break the states into groups : On vs Off vs Running vs Error. That sort of approach...

Ok, when I have some time I'll take a deeper look.

**Comment by steve-hodgkiss** [comment]
closing as 0.7 handles the same issue in a different way

**Comment by ekutner** [comment]
Wanted to thank you for this anyway. While having some issues your PR proved that the number of calls could be reduced while keeping the state correct which motivated me to handle this issue which was a known problem for a long time.

**Pull request closed without merging**
